### ISSUE TITLE
Python object

### ISSUE THREAD

**Issue by HanRunbing** [HanRunbing/MIT_CS600#1]
# How function modify the list
```
>>> def delList(lis):
	del lis[0]
>>> number = [1,2,3]
>>> delList(number)  # when call the function, reference of number is passed to list and thus it modify number itself
>>> number
[2, 3]
>>> def delList(lis):
	return lis[1:]  # Taking any slice of a creates a new list, return a new list 

>>> number = [1,2,3]
>>> delList(number)
[2, 3]
>>> number # number is not change
[1, 2, 3]
```

# Alias effect of List
```
>>> a = [1,2,3]
>>> id(a)
2198168524096
>>> b= a  # a and b refer to the same list object 
>>> b
[1, 2, 3]
>>> id(b)
2198168524096
>>> c = a[:]  # c refer to a new object 
# Note here: Taking any slice of a creates a new list. In this case the slice happens to consist of the whole list.
>>> c
[1, 2, 3]
>>> id(c)
2198168729408
>>> a[0] = 5
>>> a
[5, 2, 3]
>>> b
[5, 2, 3]
>>> c
[1, 2, 3]
>>> 
```

**Comment by HanRunbing** [comment]
# dict
```
>>> dic1 = {'A':'a','B':'b'}
>>> dic2 = dic1
>>> dic2['A'] = 'c'
>>> dic1  # Alias
{'A': 'c', 'B': 'b'}

>>> letterCounts = {}
>>> for letter in 'Mississippi':
	letterCounts[letter] = letterCounts.get(letter,0)
>>> letterCounts
{'M': 0, 'i': 0, 's': 0, 'p': 0}
>>> letterCounts.sort()
Traceback (most recent call last):
  File "<pyshell#10>", line 1, in <module>
    letterCounts.sort()
AttributeError: 'dict' object has no attribute 'sort'
>>> sorted(letterCounts)
['M', 'i', 'p', 's']
>>> items = letterCounts.items()
>>> items
dict_items([('M', 0), ('i', 0), ('s', 0), ('p', 0)])
>>> items.sort()
Traceback (most recent call last):
  File "<pyshell#14>", line 1, in <module>
    items.sort()
AttributeError: 'dict_items' object has no attribute 'sort'
```
